const tg = window.Telegram?.WebApp;
if(tg){tg.ready();tg.expand();}
const headers=()=>({'X-Telegram-Init-Data':tg?.initData||''});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(path){const r=await fetch(path,{headers:headers()});if(!r.ok)throw new Error((await r.json()).detail||'Помилка');return r.json()}
function money(n){return Number(n||0).toLocaleString('uk-UA')}
async function load(){try{const m=await api('/api/me');document.querySelector('#name').textContent=m.name;document.querySelector('#balance').textContent=money(m.balance);document.querySelector('#level').textContent=`⭐ Рівень ${m.level} • 🏡 Ферма ${m.farm_level}`;document.querySelector('#season').textContent=`${m.calendar.season} • ${m.calendar.month_name}`;document.querySelector('#weatherName').textContent=m.weather.name||m.weather;document.querySelector('#weather').textContent=m.weather.emoji||'🌤️';document.querySelector('#temp').textContent=`${m.temperature}°C`; }catch(e){document.querySelector('#content').innerHTML=`<b>Помилка:</b> ${esc(e.message)}`}}
async function render(page){const c=document.querySelector('#content');c.innerHTML='<div class="muted">Завантаження...</div>';try{let d;if(page==='fields')d=await api('/api/fields');if(page==='warehouse')d=await api('/api/warehouse');if(page==='garage')d=await api('/api/garage');if(page==='livestock')d=await api('/api/livestock');if(page==='workers')d=await api('/api/workers');if(page==='orders')d=await api('/api/orders');if(page==='fields')c.innerHTML='<h2>🌾 Поля</h2>'+d.fields.map(x=>`<div class="item"><span>${esc(x.name||('Поле №'+x.id))}</span><span class="pill">${esc(x.status||'—')}</span></div>`).join('')||'<div class="muted">Полів немає</div>';if(page==='warehouse')c.innerHTML='<h2>📦 Склад</h2>'+Object.entries(d.items||{}).map(([k,v])=>`<div class="item"><span>${esc(k)}</span><b>${money(v)} кг</b></div>`).join('')||'<div class="muted">Склад порожній</div>';if(page==='garage')c.innerHTML='<h2>🚜 Гараж</h2>'+d.vehicles.map(x=>`<div class="item"><span>${esc(x.model)}</span><span>${Math.round(x.condition_pct)}%</span></div>`).join('')||'<div class="muted">Техніки немає</div>';if(page==='livestock')c.innerHTML='<h2>🐄 Тварини</h2>'+d.animals.map(x=>`<div class="item"><span>${esc(x.animal_type)}</span><b>${x.count}</b></div>`).join('')||'<div class="muted">Тварин немає</div>';if(page==='workers')c.innerHTML='<h2>👷 Працівники</h2>'+d.workers.map(x=>`<div class="item"><span>${esc(x.worker_type)} • рівень ${x.level}</span><span>${x.active?'🟢':'🔴'}</span></div>`).join('')||'<div class="muted">Працівників немає</div>';if(page==='orders')c.innerHTML='<h2>📋 Замовлення</h2>'+Object.values(d.orders||{}).map((x,i)=>`<div class="item"><span>${esc(x.name||x.title||('Замовлення '+(i+1)))}</span><span class="pill">${money(x.reward||x.price||0)} ₴</span></div>`).join('')||'<div class="muted">Замовлень немає</div>';}catch(e){c.innerHTML=`<b>Помилка:</b> ${esc(e.message)}`}}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));load();
